### ISSUE TITLE
err="strconv.ParseFloat: parsing \"/\": invalid syntax"`

### ISSUE THREAD

**Issue by manish2479** [HewlettPackard/pcp_exporter#24] opened 2018-04-09 17:36 UTC
Hi 

I have installed pcp_exporter installed with prometheus-2.1.0.linux-amd64 and after restarting the prometheus I am getting the warning messages as below:

`caller=scrape.go:686 component="scrape manager" scrape_pool=pcp_exporter target=http://192.168.1.30:9259/metrics msg="append failed" err="strconv.ParseFloat: parsing \"/\": invalid syntax"`

So is there anything I am missing here or its a bug. I can access the metrics using url and it loads the data all fine on port 9259 but prometheus seems failing to parse those data.

Any help would be appreciated.

Thank you

**Comment by joehandzik** [comment] 2018-04-10 19:04
It could have to do with a parsing error on a specific metric. Would you be able to take a look through the metrics that you're seeing on port 9259 and paste anything in here that has a forward slash ( / )?

**Comment by manish2479** [comment] 2018-04-11 01:44
Hi Joe,

Yes that is true there are some metrics data which are having forward slash [ / ].
Here are those data.

```
pcp_network_interface_baudrate_byte / seconds{instance="0"} 1.25e+08
pcp_network_interface_baudrate_byte / seconds{instance="1"} 1.25e+08
pcp_network_interface_baudrate_byte / seconds{instance="2"} 5.36870911875e+14
pcp_network_interface_baudrate_byte / seconds{instance="4"} 1.25e+09
pcp_network_interface_baudrate_byte / seconds{instance="5"} 2.5e+09
pcp_network_interface_baudrate_byte / seconds{instance="6"} 2.5e+09
pcp_network_interface_baudrate_byte / seconds{instance="7"} 2.5e+09
pcp_network_interface_speed_mbyte / seconds{instance="0"} 119.20929
pcp_network_interface_speed_mbyte / seconds{instance="1"} 119.20929
pcp_network_interface_speed_mbyte / seconds{instance="2"} 5.12e+08
pcp_network_interface_speed_mbyte / seconds{instance="4"} 1192.0929
pcp_network_interface_speed_mbyte / seconds{instance="5"} 2384.1858
pcp_network_interface_speed_mbyte / seconds{instance="6"} 2384.1858
pcp_network_interface_speed_mbyte / seconds{instance="7"} 2384.1858
pcp_pmcd_cputime_per_pdu_in_microseconds / count 1458.7448716000608
```
Thank You

**Comment by roclark** [comment] 2018-04-11 16:23
@manish2479 thanks for bringing this up! When you get a chance, do you mind testing the patch I created on #25 and see if you are still getting any errors?

**Comment by manish2479** [comment] 2018-04-11 20:03
Hi Robert,

Sure, I will test that patch and let you know how it goes.

**Comment by manish2479** [comment] 2018-04-11 20:27
Hi Robert,

I am still getting those errors.

**Comment by roclark** [comment] 2018-04-12 15:46
Thanks for the feedback @manish2479. So you received the exact same errors as you listed before? Do you mind sharing which steps you used to test the patch out?

**Comment by manish2479** [comment] 2018-04-14 05:42
Hi Robert,

Yes I received the exact same errors as I reported. 

I applied those patch on those two file and then restarted the pcp_exporter on the client node. 

Then restarted the prometheus services on prometheus server node and right after the prometheus service is restarted I see those errors.

**Comment by roclark** [comment] 2018-04-16 14:21
@manish2479 did you also recompile the pcp_exporter after applying the patch and before starting it up again? Without recompiling, the old code will still be active. Can you try running `make` with the new patch and run that and tell me the result? If that's what you did already, we can further debug this.

**Comment by manish2479** [comment] 2018-04-17 04:51
Hi Robert,

Yes I didn't compiled it previously, when I did my last test, but now I followed your instruction and ran `make` on new patch build and still I am seeing those issues.

**Comment by roclark** [comment] 2018-04-17 17:30
Hmm, that's odd... it still seems like the patch isn't being applied, but let's verify your environment. In the `pcp_exporter` directory, can you run the following commands and share the output for each, please?
```bash
ls -l pcp_exporter
ls -l sources/
git branch
pcp_exporter -version
```

**Comment by manish2479** [comment] 2018-04-17 18:29
Here are the details.

```
# ls -l pcp_exporter
-rwxr-xr-x 1 root root 11154026 Apr 16 12:28 pcp_exporter
```

```
test ~/go/src/github.com/HewlettPackard/pcp_exporter # ls -l sources/
total 28
-rw-r--r-- 1 root     root 5698 Apr 11 13:16 pmwebapi.go
-rw-r--r-- 1 root root  5154 Feb 12 19:07 pmwebapi.go_old
-rw-r--r-- 1 root     root 3712 Apr 11 13:17 pmwebapi_test.go
-rw-r--r-- 1 root root  3250 Feb 12 19:07 pmwebapi_test.go_old
-rw-r--r-- 1 root root   322 Feb 12 19:07 source.go
```

```
test ~/go/src/github.com/HewlettPackard/pcp_exporter # git branch
* master
```

```
# ./pcp_exporter --version
pcp_exporter, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.8.3
```

**Comment by roclark** [comment] 2018-04-17 19:04
Those look good to me for the most part. I would've recommended just running
```
git pull
git checkout fix-parsing
```
to get the latest code, but it looks like you have the correct files in your `pmwebapi*.go` files, so that _shouldn't_ be an issue.

Going a step further, can you share the exact steps you use to run the new code, please? Again, I want to make sure we are making an apples-to-apples comparison here so that I can reproduce your results. I will run more of your results against our testing framework to see how the `pcp_exporter` handles them.

**Comment by manish2479** [comment] 2018-04-17 20:56
After running make, I started the `pcp_exporter` on the client node and then restarted the `prometheus` server services.

So it's just a two step process.
On Client node
```
# ./pcp_exporter
```
On Prometheus Server node
```
# ./prometheus &
```

**Comment by roclark** [comment] 2018-04-18 16:02
Alright, let me try a different tactic, because it looks like the code is being applied properly. In `sources/pmwebapi.go`, can you create a new line after line 4 with `fmt` in it? That block should now look similar to as follows:
```golang
import (
    "encoding/json"
    "fmt"
    "io/ioutil"
    "log"
    "net/http"
    "strconv"
    "strings"

    "github.com/prometheus/client_golang/prometheus"
)
```
Also, on line 152 of that same file, can you print the names of all the variables that are being sent through the switch using `fmt.Println(name)`? In other words, the end of the switch should look like this:
```golang
...
    case strings.Contains(name, " / "):
        name = strings.Replace(name, " / ", "_per_", -1)
    case strings.Contains(name, "/"):
        name = strings.Replace(name, "/", "_per_", -1)
    }
    fmt.Println(name)
    return strings.Replace(name, ".", "_", -1)
}
```

After making these changes, re-compile the code using `make` again and then run the other steps as you have been to test. As you probably guessed, this will print every metric that the `pcp_exporter` finds. If you share those metric names that are being printed out with me, I can get a better feel for what is going on and how we can fix it.

I'm assuming there are no errors when the code compiles? I find it odd that the metrics in the test work as expected, but not in your live system.

Thanks for all of your help sorting this out!

**Comment by manish2479** [comment] 2018-04-18 19:29
Hi Robert,

The metrics list is huge but here are the ones which having forward `/`.

```
mem.numa.max_bandwidth_mbyte / seconds
network.interface.speed_mbyte / seconds
network.interface.baudrate_byte / seconds
pmcd.cputime.per_pdu_in_microseconds / count
hotproc.predicate.iodemand_kbyte / seconds
disk.dev.await_milliseconds / count
disk.dev.r_await_milliseconds / count
disk.dev.w_await_milliseconds / count
disk.dev.avg_rqsz_kilobytes / count
disk.dm.await_milliseconds / count
disk.dm.r_await_milliseconds / count
disk.dm.w_await_milliseconds / count
disk.dm.avg_rqsz_kilobytes / count
disk.md.await_milliseconds / count
disk.md.r_await_milliseconds / count
disk.md.w_await_milliseconds / count
disk.md.avg_rqsz_kilobytes / count
```

So it seem we covered those 3 but rest metrics were not generated on my url output but now I can see it here with fmt code change.

**Comment by manish2479** [comment] 2018-04-23 20:29
Hi Robert,

Just wanted to see if you got a chance to take a look at those other extra metrics data with forward `/`.

**Comment by roclark** [comment] 2018-04-24 16:29
@manish2479 sorry for the delay! I got buried in another project, but I have been looking into this issue for you. I'm pretty confused as to why the metrics seem to be falling-through the `switch` block. It's also weird that it is able to pass the tests but not an actual run, so this might be triggered elsewhere from where I expected.

Circling back to make sure I understand your environment, you said that the metrics (including the ones with `/`) are visible at `http://192.168.1.30:9259/metrics`, but Prometheus is the one throwing the errors? What does your setup look like - is this a single node running the `pcp_exporter` and the same node running Prometheus? Or do you have multiple nodes running `pcp_exporter` and/or a different node for Prometheus?

It looks like you are using Go 1.8.3, yes? And which OS?

**Comment by manish2479** [comment] 2018-04-24 19:55
Hi Robert,

I have multiple node setup running pcp_exporter and different node for prometheus and OS is CentOS 7.4. 

Using the url http://192.168.1.30:9259/metrics, those disk metrics are not listed and only network metrics are listed. But with the pcp_exporter command it lists those "disks" metrics on console. 

Rest of other exporter works fine like node_exporter but when I add pcp_exporter metrics it gives the error.

Is there any debug switch I can use to get more detailed logs from prometheus.

**Comment by roclark** [comment] 2018-04-26 17:32
@manish2479 are you making these changes on every node? Or just on a single node? I wonder if the errors are coming up from different pcp_exporters than the one we are trying to debug.

**Comment by manish2479** [comment] 2018-04-26 18:44
Hi Robert,

Yes I have only two nodes configured so far with pcp and I have applied on both nodes and both nodes are reporting. 

Here is the logs output form Prometheus server.

```
level=warn ts=2018-04-26T18:36:40.371211863Z caller=scrape.go:686 component="scrape manager" scrape_pool=pcp_exporter target=http://192.168.1.30:9259/metrics msg="append failed" err="strconv.ParseFloat: parsing \"/\": invalid syntax"
level=warn ts=2018-04-26T18:36:50.029432763Z caller=scrape.go:686 component="scrape manager" scrape_pool=pcp_exporter target=http://192.168.1.33:9259/metrics msg="append failed" err="strconv.ParseFloat: parsing \"/\": invalid syntax"
level=warn ts=2018-04-26T18:36:55.348035Z caller=scrape.go:686 component="scrape manager" scrape_pool=pcp_exporter target=http://192.168.1.30:9259/metrics msg="append failed" err="strconv.ParseFloat: parsing \"/\": invalid syntax"
level=warn ts=2018-04-26T18:37:04.98202179Z caller=scrape.go:686 component="scrape manager" scrape_pool=pcp_exporter target=http://192.168.1.33:9259/metrics msg="append failed" err="strconv.ParseFloat: parsing \"/\": invalid syntax"
```
Thank You

**Comment by manish2479** [comment] 2018-04-26 20:43
Hi Robert,

I have also tried with complete fresh new install of prometheus server latest version 2.2.1 and fresh new database and still I get same error.

**Comment by roclark** [comment] 2018-05-01 15:21
@manish2479 can you send me the output you see on http://192.168.1.30:9259/metrics, please? Again, sorry for the delay, but I think I might have an idea.

**Comment by manish2479** [comment] 2018-05-01 16:04
Hi Robert,

No Problem, I have attached the file with metrics output data.

[pcp_metrics-1.txt](https://github.com/HewlettPackard/pcp_exporter/files/1964330/pcp_metrics-1.txt)

**Comment by manish2479** [comment] 2018-05-09 13:30
Hi Robert,

Just wanted to see if you were able to reproduce the issue or able to find the fix for this.

Thank You,
                   Manish

**Comment by mplachter** [comment] 2018-05-28 14:09
@roclark please check PR #26

**Comment by manish2479** [comment] 2018-06-12 02:26
Hi Robert, Matthew,

The fix came from PR [#26](https://github.com/HewlettPackard/pcp_exporter/pull/26) fixed the metrics data with forward / metrics issues. Now I am not seeing error anymore.

Thank You,
                  Manish

**Comment by roclark** [comment] 2018-07-25 21:16
@mplachter @manish2479 as mentioned in #26, very sorry for leaving you in the dark for so long! Big kudos for @mplachter for creating a fix which is now merged with master. Since it appears #26 resolved your errors @manish2479, I will close this issue.

**Comment by roclark** [comment] 2018-07-25 21:22
Whoops, realized that it is only merged with the upstream branch of `fix-parsing` and not master. Re-opening for now until it is merged with master.

**Comment by mplachter** [comment] 2018-07-25 21:27
@roclark Yeah wanted to make sure I didn't remove any other changes you guys had in flight under `fix-parsing`.

**Closed as completed** 2018-07-25 22:33 UTC
